apiVersion: v1
values:
  images:
    engine: longhornio/longhorn-engine:v1.9.0
    manager: longhornio/longhorn-manager:v1.9.0
    ui: longhornio/longhorn-ui:v1.9.0
    instanceManager: longhornio/longhorn-instance-manager:v1.9.0
    shareManager: longhornio/longhorn-share-manager:v1.9.0
    backingImageManager: longhornio/backing-image-manager:v1.9.0
    supportBundleKit: longhornio/support-bundle-kit:v0.0.55
    csiAttacher: longhornio/csi-attacher:v4.8.1
    csiProvisioner: longhornio/csi-provisioner:v5.2.0
    csiNodeDriverRegistrar: longhornio/csi-node-driver-registrar:v2.13.0
    csiResizer: longhornio/csi-resizer:v1.13.2
    csiSnapshotter: longhornio/csi-snapshotter:v8.2.0
    csiLivenessProbe: longhornio/livenessprobe:v2.15.0
    removePrivileges: bitnami/kubectl:1.33.1
patches:
  values.yaml:
    additionalImages:
      removePrivileges: "{{ .images.removePrivileges }}"
    longhorn:
      image:
        longhorn:
          engine:
            repository: "{{ registryFrom .images.engine }}/{{ repositoryFrom .images.engine }}"
            tag: "{{ tagFrom .images.engine }}"
          manager:
            repository: "{{ registryFrom .images.manager }}/{{ repositoryFrom .images.manager }}"
            tag: "{{ tagFrom .images.manager }}"
          ui:
            repository: "{{ registryFrom .images.ui }}/{{ repositoryFrom .images.ui }}"
            tag: "{{ tagFrom .images.ui }}"
          instanceManager:
            repository: "{{ registryFrom .images.instanceManager }}/{{ repositoryFrom .images.instanceManager }}"
            tag: "{{ tagFrom .images.instanceManager }}"
          shareManager:
            repository: "{{ registryFrom .images.shareManager }}/{{ repositoryFrom .images.shareManager }}"
            tag: "{{ tagFrom .images.shareManager }}"
          backingImageManager:
            repository: "{{ registryFrom .images.backingImageManager }}/{{ repositoryFrom .images.backingImageManager }}"
            tag: "{{ tagFrom .images.backingImageManager }}"
          supportBundleKit:
            repository: "{{ registryFrom .images.supportBundleKit }}/{{ repositoryFrom .images.supportBundleKit }}"
            tag: "{{ tagFrom .images.supportBundleKit }}"
        csi:
          attacher:
            repository: "{{ registryFrom .images.csiAttacher }}/{{ repositoryFrom .images.csiAttacher }}"
            tag: "{{ tagFrom .images.csiAttacher }}"
          provisioner:
            repository: "{{ registryFrom .images.csiProvisioner }}/{{ repositoryFrom .images.csiProvisioner }}"
            tag: "{{ tagFrom .images.csiProvisioner }}"
          nodeDriverRegistrar:
            repository: "{{ registryFrom .images.csiNodeDriverRegistrar }}/{{ repositoryFrom .images.csiNodeDriverRegistrar }}"
            tag: "{{ tagFrom .images.csiNodeDriverRegistrar }}"
          resizer:
            repository: "{{ registryFrom .images.csiResizer }}/{{ repositoryFrom .images.csiResizer }}"
            tag: "{{ tagFrom .images.csiResizer }}"
          snapshotter:
            repository: "{{ registryFrom .images.csiSnapshotter }}/{{ repositoryFrom .images.csiSnapshotter }}"
            tag: "{{ tagFrom .images.csiSnapshotter }}"
          livenessProbe:
            repository: "{{ registryFrom .images.csiLivenessProbe }}/{{ repositoryFrom .images.csiLivenessProbe }}"
            tag: "{{ tagFrom .images.csiLivenessProbe }}"
