longhorn:
  nameOverride: k8s-longhorn
  defaultSettings:
    # backupTarget specifies the bucket where the backup will be stored.
    backupTarget: ~
    backupTargetCredentialSecret: ~
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    deletingConfirmationFlag: true