longhorn:
  nameOverride: k8s-longhorn
  privateRegistry:
    registrySecret: ces-container-registries
  defaultSettings:
    # backupTarget specifies the bucket where the backup will be stored.
    backupTarget: ~
    backupTargetCredentialSecret: ~
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    deletingConfirmationFlag: true
  image:
    removePrivileges:
      repository: bitnami/kubectl
      tag: 1.30.6