{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backing-image-data-source
  namespace: {{ include "release_namespace" . }}
  labels: {{- include "longhorn.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      longhorn.io/component: backing-image-data-source
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: longhorn-manager
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "release_namespace" . }}
        - podSelector:
            matchLabels:
              longhorn.io/component: instance-manager
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "release_namespace" . }}
        - podSelector:
            matchLabels:
              longhorn.io/component: backing-image-manager
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "release_namespace" . }}
        - podSelector:
            matchLabels:
              longhorn.io/component: backing-image-data-source
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "release_namespace" . }}
{{- end }}