apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.4.1
data:
  default-setting.yaml: |-
    node-down-pod-deletion-policy: delete-both-statefulset-and-deployment-pod
    {{- if .Values.backup.target }}
    backup-target: {{ .Values.backup.target.url }}
    backup-target-credential-secret: {{ .Values.backup.target.secretName }}
    {{- end }}