apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.longhorn.defaultSettings.backupTargetCredentialSecret }}
  namespace: longhorn-system
  labels:
    app: ces
    app.kubernetes.io/name: k8s-longhorn
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.backup.target.secret.aws_access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backup.target.secret.aws_secret_access_key | b64enc }}
  AWS_ENDPOINTS: {{ .Values.backup.target.secret.aws_endpoint | b64enc }}